version: latest
services:
  work_space:
    build:
      context: 
        ./work_space
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/torch/notebooks
      - ./data:/torch/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]